Make cert-manager + Vault workflow more configurable
cert-manager/testing-addons pull request #14
Opened 2022-07-08 10:21 UTC by lonelyCZ

Signed-off-by: lonelyCZ <531187475@qq.com>

Fixes #9

2022-07-08 10:31 UTC, lonelyCZ commented
There are some warnings outputed refer [#22004](https://github.com/hashicorp/terraform/issues/22004), I don't find an easy way to silience it and only set `-compact-warnings` to reduce the outputs. There is [a way in terragrunt] (https://github.com/gruntwork-io/terragrunt/issues/1395#issuecomment-754251066) recommended to deal it, do we need to use it?

```
Warnings:

- Value for undeclared variable
- Value for undeclared variable

To see the full warning notes, run Terraform without -compact-warnings.
```

2022-07-08 10:37 UTC, lonelyCZ commented
/assign @irbekrm

2022-07-10 19:01 UTC, irbekrm requested changes
Thanks @lonelyCZ !

Good work on this. I've added a few small nits, otherwise happy to lgtm 👍🏼

2022-07-10 19:01 UTC, irbekrm commented on cm-vault/cm-config/variables.tf
> +}
Nit: newline

2022-07-10 19:01 UTC, irbekrm commented on cm-vault/cm-install/variables.tf
> +  default = "v1.8.0"
Suggestion: bump to the latest patch version, which is currently `v1.8.2` https://github.com/cert-manager/cert-manager/releases/tag/v1.8.2

2022-07-10 19:01 UTC, irbekrm commented on cm-vault/common.tfvars
> +# The root domain of the Vault PKI. Default is ""
I think the default is "cert-manager.io" not ""?

2022-07-11 12:49 UTC, lonelyCZ commented
Thanks for your reviews! I have updated it, please review it again.

/assign @irbekrm

2022-07-11 19:01 UTC, irbekrm commented
Thank you @lonelyCZ !

/lgtm
/approve

2022-07-11 19:01 UTC, merged