[WIP]Initialize Cert-manager with ingress certs via ingress-shim workflow
cert-manager/testing-addons pull request #37
Opened 2022-08-28 15:43 UTC by lonelyCZ

Signed-off-by: lonelyCZ <531187475@qq.com>

Fixes #35

2022-08-29 03:30 UTC, lonelyCZ commented
Hi, @irbekrm I initialize the workflow of deploying ingress, could you help me check whether the workflow is correct? I plan to make it support `ACME` after the initial workflw is correct in next PR.

And I have a question, do we need to deploy an example APP to use the ingress, such as an easy web app?

/assign @irbekrm

2022-08-31 05:14 UTC, irbekrm requested changes
Hi @lonelyCZ thank you for working on the Ingress dependency!

This looks good to me overall 👍🏼 

I have added a couple suggestions for parameterization.

I have tested this PR by deploying the default configuration to a Kind cluster and checking that the NGINX Ingress has loaded the correct TLS certificate for the `example.com` hostname using [ingress-nginx kubectl plugin](https://kubernetes.github.io/ingress-nginx/kubectl-plugin/) (`kubectl ingress-nginx certs --host example.com --namespace ingress-nginx`). I saw that the correct cert was loaded 👍🏼 
I will test end to end with an external IP once we have an ACME issuer.

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/common.tfvars
> +# You can check the mapping between the Ingress-nginx Helm version and the Ingress-nginx APP version by executing `helm search repo ingress-nginx/ingress-nginx -l`
This is a good tip 👍🏼

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/common.tfvars
> +# Path to the kubeconfig file to use for connecting kubernetes cluster. Default is "~/.kube/config"
We should also allow to configure `ingress_hostname` at this level as every user will want to provide a custom value for it.

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/cm-config/main.tf
> +    "kind"       = "ClusterIssuer"
Suggestion: make this an `Issuer`. It only needs to issue one certificate in a namespace that we know.

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/ingress-config/main.tf
> +                "name" = "ingress-test-service"
The name of the service should be parameterized (the user will want to use this Ingress to route traffic to some Service that they have)

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/ingress-config/main.tf
> +                  "number" = 80
The port too should be parameterized

2022-08-31 05:14 UTC, irbekrm commented on cm-ingress/common.tfvars
> +ingress_nginx_arguments = {
This should also include [load balancer IP](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#:~:text=controller.service.loadBalancerIP)

2022-08-31 05:20 UTC, irbekrm commented
> And I have a question, do we need to deploy an example APP to use the ingress, such as an easy web app?

I think it is OK without as long as we parameterize the [backend service name](https://github.com/cert-manager/testing-addons/pull/37#discussion_r959158940) and port. The user can then deploy whichever app with a Kubernetes Service they want.
Maybe we can add a link to [example kuard deployment](https://cert-manager.io/docs/tutorials/acme/nginx-ingress/#step-4---deploy-an-example-service) in the Readme for cm-ingress module.

2022-08-31 07:57 UTC, lonelyCZ commented
PTAL. 

/assign @irbekrm

2022-09-02 13:40 UTC, irbekrm approved these changes
Thank you for making the changes @lonelyCZ , this all now makes sense 👍🏼 

Thanks for adding the Readme too, it's very good.

I guess the next step will be to add the ACME issuer.

/lgtm

2022-09-02 13:40 UTC, merged